### ISSUE TITLE
Points System Cog

### ISSUE THREAD

**Issue by jacobmcilravey** [Aioxas/ax-cogs#4]
Would it be possible to change the balance command from !balance to !points balance? It interferes with the vanilla economy cog. I wanted to have a currency and point system on the bot. 

Adding to this, when actually trying to grant points, I get an error.
http://sentry.imjake.me/share/issue/352e313438/

Thanks so much.

**Comment by Aioxas** [comment]
I apologize for the late reply. I haven't been able to do any coding nowadays. The vainilla economy cog has the command bank balance, unless you edited the economy cog. I did miss up on adding the help strings on the balance command. Either way, how would you set up both bank balance and points balance?

**Comment by Aioxas** [comment]
Can you also tell me what were the arguments of the command you were using? for add_member

**Comment by Aioxas** [comment]
Closed due to inactivity
